In [2]:
import fsemu
import numpy as np

In [3]:
circ = [('H',(0,)), ('CNOT', (0,1)), ('CNOT', (0,2)), ('CNOT', (0,3))]
final  = fsemu.simulate(4, circ)

In [4]:
fsemu.get_probabilities(final)

{'0000': np.float64(0.4999999999999999),
 '0001': np.float64(0.0),
 '0010': np.float64(0.0),
 '0011': np.float64(0.0),
 '0100': np.float64(0.0),
 '0101': np.float64(0.0),
 '0110': np.float64(0.0),
 '0111': np.float64(0.0),
 '1000': np.float64(0.0),
 '1001': np.float64(0.0),
 '1010': np.float64(0.0),
 '1011': np.float64(0.0),
 '1100': np.float64(0.0),
 '1101': np.float64(0.0),
 '1110': np.float64(0.0),
 '1111': np.float64(0.4999999999999999)}

In [5]:
zerostate = fsemu.init_state(4)

In [6]:
fsemu.expectation_value(final, [('Z', (0,)), ('Z', (3,))])

np.float64(0.9999999999999998)

In [7]:
fsemu.get_zcorrelator(final, 0,3)

np.float64(0.9999999999999998)

In [10]:
fsemu.sample_state(final)

(1, 1, 1, 1)

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

result = np.multiply(a, b)
print(result)

[[ 7 16 27]
 [40 55 72]]


In [12]:
test1 = np.array([[[1,1],[1,1]],[[1,1],[1,1]]])


In [13]:
test1.shape

(2, 2, 2)

In [8]:
import mps
import numpy as np
import fsemu

In [9]:
randomstate = mps.init_state_random(4, 2)
zerostate = mps.init_state_zero(4)

In [10]:
zerostate

[array([[[1.],
         [0.]]]),
 array([[[1.],
         [0.]]]),
 array([[[1.],
         [0.]]]),
 array([[[1.],
         [0.]]])]

In [ ]:
zerostate = mps.apply_1q_gate(zerostate, (0,), 'H')
print(zerostate)
zerostate = mps.apply_2q_gate_nn(zerostate, (0,1), 'CNOT')
print(zerostate)

IndexError: tuple index out of range

In [7]:
zerostate

[array([[[1.],
         [0.]]]),
 array([[[1.],
         [0.]]]),
 array([[[1.],
         [0.]]]),
 array([[[1.],
         [0.]]])]

In [12]:
zerostate = mps.apply_1q_gate(zerostate, 2, mps.gates['Y'])

In [13]:
zerostate

[array([[[1.],
         [0.]]]),
 array([[[1.],
         [0.]]]),
 array([[[0.+0.70710678j],
         [0.-0.70710678j]]]),
 array([[[1.],
         [0.]]])]

In [3]:
flatmps = mps.give_flat(zerostate)

In [4]:
flatfs = fsemu.init_state(4)

In [5]:
print(flatmps)
print(flatfs)

[[[[1. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]
[[[[1. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


In [6]:
a = np.array([1,2])
b= np.array([3,4])


In [11]:
np.concatenate([a, b])

array([1, 2, 3, 4])